// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using StormEyeApi.Data;

#nullable disable

namespace StormEyeApi.Migrations
{
    [DbContext(typeof(StormEyeContext))]
    [Migration("20250602121228_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StormEyeApi.Models.CartilhaMapeada", b =>
                {
                    b.Property<int>("IdCartilhaM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCartilhaM"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdCatastrofeM")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCartilhaM");

                    b.HasIndex("IdCatastrofeM");

                    b.ToTable("TGS_CARTILHA_MAPEADA", (string)null);
                });

            modelBuilder.Entity("StormEyeApi.Models.CatastrofeMapeada", b =>
                {
                    b.Property<int>("IdCatastrofeM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCatastrofeM"));

                    b.Property<bool>("AtivoM")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("NomeCatastrofeM")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SintomaCatastrofeM")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCatastrofeM");

                    b.ToTable("TGS_CATASTROFE_MAPEADA", (string)null);
                });

            modelBuilder.Entity("StormEyeApi.Models.CartilhaMapeada", b =>
                {
                    b.HasOne("StormEyeApi.Models.CatastrofeMapeada", "CatastrofeMapeada")
                        .WithMany("Cartilhas")
                        .HasForeignKey("IdCatastrofeM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatastrofeMapeada");
                });

            modelBuilder.Entity("StormEyeApi.Models.CatastrofeMapeada", b =>
                {
                    b.Navigation("Cartilhas");
                });
#pragma warning restore 612, 618
        }
    }
}
